name: Taskorium workflow

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'src**'
      - '.github/workflows/workflow.yml'
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Format code
        working-directory: ./src/backend
        run: dotnet format --verify-no-changes
      - name: Restore dependencies
        working-directory: ./src/backend
        run: dotnet restore
      - name: Build
        working-directory: ./src/backend
        run: dotnet build --no-restore
    